import { useEffect, useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styled from '@emotion/styled';

const Home: NextPage = () => {
  const [count, setCount] = useState([1]);

  const clickHandler = () => {
    setCount([...count, count[count.length - 1] + 1]);
  };

  const pusherFunc = () =>{ 
    Pusher.logToConsole = true;

    const pusher = newPusher('key', options {
      custer: 'eu'
    })
  }

  useEffect(()=>{
    pusherFunc()
  },[])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Container>
        <button onClick={clickHandler}>Click me!</button>
        {count.map((value, key) => (
          <li key={key}>{value}</li>
        ))}
      </Container>
    </div>
  );
};

export default Home;

const Container = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;
